version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./src:/app/src
    container_name: bot
    depends_on:
      - postgres
    network_mode: host
  postgres:
    container_name: bot-db
    image: postgres:12
    env_file: .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - botdb-prod-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-prod-data:/var/lib/pgadmin

volumes:
  botdb-prod-data:
  pgadmin-prod-data: